-- ----------------------------------------------------------------
-- DIMENSION TABLES
-- ----------------------------------------------------------------
-- Generated by Claude

-- SCD Type 1s: category and product
-- Name changes for these dimensions IMO matter a lot less for historical data since I don't expect them to happen commonly... - Peter
CREATE TABLE IF NOT EXISTS dim_category (
    category_id   INT          IDENTITY(1,1) PRIMARY KEY,
    category_name VARCHAR(50)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS dim_product (
    sku                   VARCHAR(20)   NOT NULL PRIMARY KEY,
    product_name          VARCHAR(100)  NOT NULL,
    category_id           INT           REFERENCES dim_category(category_id),
    unit_cost_usd         DECIMAL(10,2),
    unit_retail_price_usd DECIMAL(10,2)
);

-- SCD Type 2: tracks supplier name changes over time
-- (e.g. mergers, rebrands)
-- Necessary because we don't want to lose data from a supplier rebranding or merging, and treating them as separate entities before/after merger is gonna mess with the numbers - Peter
CREATE TABLE IF NOT EXISTS dim_supplier (
    supplier_id    INT          IDENTITY(1,1) PRIMARY KEY,
    supplier_name  VARCHAR(100) NOT NULL,
    effective_date DATE         NOT NULL,
    expiry_date    DATE,                    -- NULL = currently active
    is_current     BOOL      NOT NULL DEFAULT TRUE
);

-- SCD Type 2: tracks store name changes over time
-- Store names may or may not change over time, but I wanted to be on the safe side to not mess up historical data analysis - Peter
CREATE TABLE IF NOT EXISTS dim_store (
    store_id       INT          IDENTITY(1,1) PRIMARY KEY,
    store_name     VARCHAR(50)  NOT NULL,
    effective_date DATE         NOT NULL,
    expiry_date    DATE,                    -- NULL = currently active
    is_current     BOOL     NOT NULL DEFAULT TRUE
);

-- ----------------------------------------------------------------
-- FACT TABLES
-- ----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fact_transactions (
    transaction_id    VARCHAR(20)   NOT NULL PRIMARY KEY,
    customer_id       VARCHAR(20),
    transaction_date  TIMESTAMP,
    store_id          INT           REFERENCES dim_store(store_id),
    sku               VARCHAR(20)   REFERENCES dim_product(sku),
    quantity_sold     INT,
    unit_price_usd    DECIMAL(10,2),
    discount_rate     DECIMAL(5,4),
    total_sales_usd   DECIMAL(10,2),
    payment_method    VARCHAR(30),
    shrinkage_usd     DECIMAL(10,2),
    return_flag       BOOL
);

CREATE TABLE IF NOT EXISTS fact_supplier_orders (
    order_id               VARCHAR(20)   NOT NULL PRIMARY KEY,
    order_date             TIMESTAMP,
    supplier_id            INT           REFERENCES dim_supplier(supplier_id),
    store_id               INT           REFERENCES dim_store(store_id),
    sku                    VARCHAR(20)   REFERENCES dim_product(sku),
    qty_ordered            INT,
    qty_received           INT,
    total_order_value_usd  DECIMAL(10,2),
    expected_delivery_date DATE,
    actual_delivery_date   TIMESTAMP,
    fill_rate_pct          DECIMAL(5,2),
    invoice_matched_flag   BOOL
);

CREATE TABLE IF NOT EXISTS fact_inventory (
    inventory_id          INT          IDENTITY(1,1) PRIMARY KEY, -- No natural primary key in this table, and using a composite key of (sku, store_id, last_restock_date) risks some keys messing up because there can be multiple combos of (sku, store_id) that has a null last_restock_date (e.g. (SKU-1024, 2, NULL)), so this is necessary... - Peter
    sku                   VARCHAR(20)  REFERENCES dim_product(sku),
    store_id              INT          REFERENCES dim_store(store_id),
    supplier_id           INT          REFERENCES dim_supplier(supplier_id),
    units_on_hand         INT,
    reorder_point         INT,
    days_on_shelf         INT,
    last_restock_date     TIMESTAMP,
    out_of_stock_days_30d INT,
    expiry_date           DATE,
    markdown_flag         BOOL
);

-- ----------------------------------------------------------------
-- STAGING TABLES
-- ----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS staging_transactions (
    transaction_id   VARCHAR(20),
    customer_id      VARCHAR(20),
    transaction_date TIMESTAMP,
    store_name       VARCHAR(50),
    category_name    VARCHAR(50),
    sku              VARCHAR(20),
    product_name     VARCHAR(100),
    quantity_sold    INT,
    unit_price_usd   DECIMAL(12,2),
    discount_rate    DECIMAL(5,4),
    total_sales_usd  DECIMAL(12,2),
    payment_method   VARCHAR(30),
    cashier_id       VARCHAR(20),
    shrinkage_usd    DECIMAL(10,2),
    return_flag      BOOL
);

CREATE TABLE IF NOT EXISTS staging_inventory (
    sku                   VARCHAR(20),
    product_name          VARCHAR(100),
    category_name         VARCHAR(50),
    store_name            VARCHAR(50),
    supplier_name         VARCHAR(100),
    units_on_hand         INT,
    reorder_point         INT,
    days_on_shelf         INT,
    last_restock_date     TIMESTAMP,
    unit_cost_usd         DECIMAL(10,2),
    unit_retail_price_usd DECIMAL(10,2),
    out_of_stock_days_30d INT,
    expiry_date           DATE,
    markdown_flag         BOOL
);

CREATE TABLE IF NOT EXISTS staging_supplier_orders (
    order_id               VARCHAR(20),
    order_date             TIMESTAMP,
    supplier_name          VARCHAR(100),
    category_name          VARCHAR(50),
    sku                    VARCHAR(20),
    product_name           VARCHAR(100),
    store_name             VARCHAR(50),
    qty_ordered            INT,
    qty_received           INT,
    unit_cost_usd          DECIMAL(10,2),
    total_order_value_usd  DECIMAL(10,2),
    expected_delivery_date DATE,
    actual_delivery_date   TIMESTAMP,
    fill_rate_pct          DECIMAL(5,2),
    invoice_matched_flag   BOOL
);